theme: jekyll-theme-minimal
title: Grata Viatorem - Welcome Traveler
description: Just a site to post things, past, present, and future. Updates are periodic or whenever I feel like posting something I'm doing.
